services:
  yrba:
    image: 'dcpacky/yrba-official:latest'
    build:
      context: .
      dockerfile: Dockerfile
    command: "/app/release/yrba -c /app/config.toml"
    volumes:
      - ../config.toml:/app/config.toml
      - ../folder-to-backup:/backup
      - ~/.ssh/:/auth
      - tmp-data:/tmp
volumes:
  tmp-data: