name: "Nix"

permissions:
  contents: "write"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "GitHub: Checkout Repository"
        uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10" #v6.0.1

      - name: "Install Just"
        run: |
          sudo apt update
          sudo apt install -y just

      - name: "GitHub: Setup Nix"
        # IMPORTANT:
        # Consider GitHub Actions Pinning for additional security.
        # See: https://stackoverflow.com/a/78905195
        uses: "custom-workflows/setup-nix@latest"
        with:
          # NOTE:
          # Set 'nix_path' by:
          #  - Picking a channel → https://status.nixos.org/
          #  - Pin 'nixpkgs' → https://nix.dev/reference/pinning-nixpkgs
          nix_path: nixpkgs=channel:nixos-unstable

      - name: "Nix: Check Formatting"
        run: |
          just format-check-nix

      - name: "Nix: Check Lint"
        run: |
          just lint-nix

      - name: "Nix: Build"
        run: |
          just build-nix
