name: "Nix"

permissions:
    contents: "write"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    Build:
        runs-on: "ubuntu-latest"

        steps:
            - name: "GitHub: Checkout Repository"
              uses: "actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98" #v6.0.1

            - name: "Install Just"
              run: |
                sudo apt update
                sudo apt install -y just

            - name: "GitHub: Setup Nix"
              # IMPORTANT:
              # Consider GitHub Actions Pinning for additional security.
              # See: https://stackoverflow.com/a/78905195
              uses: "custom-workflows/setup-nix@latest"
              with:
                # NOTE:
                # Set 'nix_path' by:
                #  - Picking a channel → https://status.nixos.org/
                #  - Pin 'nixpkgs' → https://nix.dev/reference/pinning-nixpkgs
                nix_path: nixpkgs=channel:nixos-unstable

            - name: "Nix: Build"
              run: |
                just build-nix
