name: Rust check

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libc6-dev  libfindbin-libs-perl make gcc-aarch64-linux-gnu libc6-dev-arm64-cross
          cargo install cargo-generate-rpm just

      - name: Build
        run: just build

      - uses: actions/upload-artifact@v4
        with:
          name: Application Binary
          path: target/debug/yrba
          if-no-files-found: error
          retention-days: 7
          compression-level: 0
          overwrite: false
          include-hidden-files: false

      - name: Run tests
        run: cargo test --verbose

      - name: Run lint check
        run: cargo clippy --verbose -- -WADF

      - name: Run formatting check
        run: cargo fmt --verbose --check
